<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class PermissionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table(table: 'permissions')->insert([
            ['id' => 1, 'name' => 'Truy cập trang dashboard'],
            ['id' => 2, 'name' => 'Thêm chức vụ nhân viên'],
            ['id' => 3, 'name' => 'Bật/tắt quyền'],
            ['id' => 4, 'name' => 'Danh sách quyền truy cập'],
            ['id' => 5, 'name' => 'Danh sách nhân viên'],
            ['id' => 6, 'name' => 'Thêm mới nhân viên'],
            ['id' => 7, 'name' => 'Lưu nhân viên mới'],
            ['id' => 8, 'name' => 'Sửa thông tin nhân viên'],
            ['id' => 9, 'name' => 'Cập nhật thông tin nhân viên'],
            ['id' => 10, 'name' => 'Danh sách nhà cung cấp'],
            ['id' => 11, 'name' => 'Danh sách nhà cung cấp đã xóa'],
            ['id' => 12, 'name' => 'Khôi phục nhà cung cấp'],
            ['id' => 13, 'name' => 'Thêm mới nhà cung cấp'],
            ['id' => 14, 'name' => 'Lưu nhà cung cấp mới'],
            ['id' => 15, 'name' => 'Sửa nhà cung cấp'],
            ['id' => 16, 'name' => 'Cập nhật nhà cung cấp'],
            ['id' => 17, 'name' => 'Xóa nhà cung cấp'],
            ['id' => 18, 'name' => 'Danh sách nhà cung cấp'],
            ['id' => 19, 'name' => 'Thêm mới nhà cung cấp'],
            ['id' => 20, 'name' => 'Lưu nhà cung cấp mới'],
            ['id' => 21, 'name' => 'Sửa nhà cung cấp'],
            ['id' => 22, 'name' => 'Cập nhật nhà cung cấp'],
            ['id' => 23, 'name' => 'Lấy địa điểm theo ID khách hàng'],
            ['id' => 24, 'name' => 'Đặt địa chỉ mặc định'],
            ['id' => 25, 'name' => 'Lấy địa điểm của khách hàng'],
            ['id' => 26, 'name' => 'Xóa địa điểm'],
            ['id' => 27, 'name' => 'Lấy địa điểm'],
            ['id' => 28, 'name' => 'Danh sách nhân viên'],
            ['id' => 29, 'name' => 'Thêm mới nhân viên'],
            ['id' => 30, 'name' => 'Lưu nhân viên mới'],
            ['id' => 31, 'name' => 'Sửa thông tin nhân viên'],
            ['id' => 32, 'name' => 'Cập nhật thông tin nhân viên'],
            ['id' => 33, 'name' => 'Danh sách slider'],
            ['id' => 34, 'name' => 'Thêm mới slider'],
            ['id' => 35, 'name' => 'Lưu slider mới'],
            ['id' => 36, 'name' => 'Chi tiết slider'],
            ['id' => 37, 'name' => 'Sửa slider'],
            ['id' => 38, 'name' => 'Cập nhật slider'],
            ['id' => 39, 'name' => 'Xóa slider'],
            ['id' => 40, 'name' => 'Danh sách thương hiệu'],
            ['id' => 41, 'name' => 'Thêm mới thương hiệu'],
            ['id' => 42, 'name' => 'Lưu thương hiệu mới'],
            ['id' => 43, 'name' => 'Sửa thương hiệu'],
            ['id' => 44, 'name' => 'Cập nhật thương hiệu'],
            ['id' => 45, 'name' => 'Danh sách hợp đồng'],
            ['id' => 46, 'name' => 'Thêm mới hợp đồng'],
            ['id' => 47, 'name' => 'Lưu hợp đồng mới'],
            ['id' => 48, 'name' => 'Sửa hợp đồng'],
            ['id' => 49, 'name' => 'Cập nhật hợp đồng'],
            ['id' => 50, 'name' => 'Gửi xác nhận cho quản lý'],
            ['id' => 51, 'name' => 'Gửi xác nhận cho khách hàng'],
            ['id' => 52, 'name' => 'Xác nhận hợp đồng'],
            ['id' => 53, 'name' => 'Từ chối hợp đồng'],
            ['id' => 54, 'name' => 'Khách hàng phê duyệt'],
            ['id' => 55, 'name' => 'Khách hàng từ chối'],
            ['id' => 56, 'name' => 'Khách hàng phê duyệt với token'],
            ['id' => 57, 'name' => 'Khách hàng từ chối với token'],
            ['id' => 58, 'name' => 'Sửa hợp đồng theo số hợp đồng'],
            ['id' => 59, 'name' => 'Cập nhật hợp đồng theo số hợp đồng'],
            ['id' => 60, 'name' => 'Xem hợp đồng PDF'],
            ['id' => 61, 'name' => 'Gửi PDF cho quản lý'],
            ['id' => 62, 'name' => 'Từ chối hợp đồng'],
            ['id' => 63, 'name' => 'Lịch sử trạng thái hợp đồng'],
            ['id' => 64, 'name' => 'Chi tiết hợp đồng'],
            ['id' => 65, 'name' => 'Danh sách bán hàng'],
            ['id' => 66, 'name' => 'Thêm đơn hàng'],
            ['id' => 67, 'name' => 'Lưu đơn hàng mới'],
            ['id' => 68, 'name' => 'Lưu đơn hàng hợp đồng'],
            ['id' => 69, 'name' => 'Sửa đơn hàng'],
            ['id' => 70, 'name' => 'Cập nhật đơn hàng'],
            ['id' => 71, 'name' => 'Cập nhật trạng thái đơn hàng'],
            ['id' => 72, 'name' => 'Chi tiết đơn hàng'],
            ['id' => 73, 'name' => 'Yêu cầu hủy đơn hàng'],
            ['id' => 74, 'name' => 'Thêm đơn hàng có hợp đồng'],
            ['id' => 75, 'name' => 'Danh sách xe'],
            ['id' => 76, 'name' => 'Thêm mới xe'],
            ['id' => 77, 'name' => 'Lưu xe mới'],
            ['id' => 78, 'name' => 'Sửa xe'],
            ['id' => 79, 'name' => 'Cập nhật xe'],
            ['id' => 80, 'name' => 'Danh sách loại hợp đồng'],
            ['id' => 81, 'name' => 'Thêm loại hợp đồng'],
            ['id' => 82, 'name' => 'Lưu loại hợp đồng mới'],
            ['id' => 83, 'name' => 'Sửa loại hợp đồng'],
            ['id' => 84, 'name' => 'Cập nhật loại hợp đồng'],
            ['id' => 85, 'name' => 'Danh sách khách hàng'],
            ['id' => 86, 'name' => 'Thêm mới khách hàng'],
            ['id' => 87, 'name' => 'Lưu khách hàng mới'],
            ['id' => 88, 'name' => 'Danh sách sản phẩm'],
            ['id' => 89, 'name' => 'Thêm mới sản phẩm'],
            ['id' => 90, 'name' => 'Lưu sản phẩm mới'],
            ['id' => 91, 'name' => 'Sửa sản phẩm'],
            ['id' => 92, 'name' => 'Cập nhật sản phẩm'],
            ['id' => 93, 'name' => 'Danh sách đơn hàng nhập'],
            ['id' => 94, 'name' => 'Thêm đơn hàng nhập'],
            ['id' => 95, 'name' => 'Lưu đơn hàng nhập mới'],
            ['id' => 96, 'name' => 'Sửa đơn hàng nhập'],
            ['id' => 97, 'name' => 'Cập nhật đơn hàng nhập'],
            ['id' => 98, 'name' => 'Chi tiết đơn hàng nhập'],
            ['id' => 99, 'name' => 'Yêu cầu hủy đơn hàng nhập'],
            ['id' => 100, 'name' => 'Danh sách yêu cầu hủy đang chờ'],
            ['id' => 101, 'name' => 'Hủy đơn hàng nhập'],
            ['id' => 102, 'name' => 'Xác nhận đơn hàng nhập'],
            ['id' => 103, 'name' => 'Tự động cập nhật trạng thái đơn hàng nhập'],
            ['id' => 104, 'name' => 'Danh sách yêu cầu mới đang chờ'],
            ['id' => 105, 'name' => 'Kiểm tra trạng thái đơn hàng nhập'],
            ['id' => 106, 'name' => 'Cập nhật trạng thái đơn hàng nhập'],
            ['id' => 107, 'name' => 'Từ chối đơn hàng nhập'],
            ['id' => 108, 'name' => 'Danh sách đơn vị'],
            ['id' => 109, 'name' => 'Thêm mới đơn vị'],
            ['id' => 110, 'name' => 'Lưu đơn vị mới'],
            ['id' => 111, 'name' => 'Sửa đơn vị'],
            ['id' => 112, 'name' => 'Cập nhật đơn vị'],
            ['id' => 113, 'name' => 'Xóa đơn vị'],
            ['id' => 114, 'name' => 'Danh sách loại xe'],
            ['id' => 115, 'name' => 'Thêm mới loại xe'],
            ['id' => 116, 'name' => 'Lưu loại xe mới'],
            ['id' => 117, 'name' => 'Sửa loại xe'],
            ['id' => 118, 'name' => 'Cập nhật loại xe'],
            ['id' => 119, 'name' => 'Xóa loại xe'],
            ['id' => 120, 'name' => 'Danh sách danh mục'],
            ['id' => 121, 'name' => 'Thêm mới danh mục'],
            ['id' => 122, 'name' => 'Lưu danh mục mới'],
            ['id' => 123, 'name' => 'Sửa danh mục'],
            ['id' => 124, 'name' => 'Cập nhật danh mục'],
            ['id' => 125, 'name' => 'Xóa danh mục'],
            ['id' => 126, 'name' => 'Danh sách xếp hạng khách hàng'],
            ['id' => 127, 'name' => 'Thêm mới xếp hạng khách hàng'],
            ['id' => 128, 'name' => 'Lưu xếp hạng khách hàng mới'],
            ['id' => 129, 'name' => 'Sửa xếp hạng khách hàng'],
            ['id' => 130, 'name' => 'Cập nhật xếp hạng khách hàng'],
            ['id' => 131, 'name' => 'Xóa xếp hạng khách hàng'],
            ['id' => 132, 'name' => 'Danh sách chuyến xe'],
            ['id' => 133, 'name' => 'Thêm mới chuyến xe'],
            ['id' => 134, 'name' => 'Lưu chuyến xe mới'],
            ['id' => 135, 'name' => 'Sửa chuyến xe'],
            ['id' => 136, 'name' => 'Cập nhật chuyến xe'],
            ['id' => 137, 'name' => 'Xóa chuyến xe'],
            ['id' => 138, 'name' => 'Chi tiết chuyến xe'],
            ['id' => 139, 'name' => 'Danh sách log'],
            ['id' => 140, 'name' => 'Danh sách tồn kho'],
            ['id' => 141, 'name' => 'Xuất variations'],
            ['id' => 142, 'name' => 'Nhập variations'],
            ['id' => 143, 'name' => 'Lưu variations'],
            ['id' => 144, 'name' => 'Lấy chi tiết tồn kho'],
            ['id' => 145, 'name' => 'Lịch sử nhập hàng'],
            ['id' => 146, 'name' => 'Cập nhật hàng loạt sản phẩm'],
            ['id' => 147, 'name' => 'Danh sách loại biến thể'],
            ['id' => 148, 'name' => 'Thêm mới loại biến thể'],
            ['id' => 149, 'name' => 'Lưu loại biến thể mới'],
            ['id' => 150, 'name' => 'Thêm giá trị mới'],
            ['id' => 151, 'name' => 'Sửa loại biến thể'],
            ['id' => 152, 'name' => 'Cập nhật loại biến thể'],
            ['id' => 153, 'name' => 'Danh sách lịch sử chuyển tiền'],
            ['id' => 154, 'name' => 'Thêm mới lịch sử chuyển tiền'],
            ['id' => 155, 'name' => 'Xác nhận lịch sử chuyển tiền'],
            ['id' => 156, 'name' => 'Xác nhận hợp đồng của khách hàng'],
            ['id' => 157, 'name' => 'Từ chối hợp đồng của khách hàng'],
            ['id' => 158, 'name' => 'Lấy tin nhắn'],
            ['id' => 159, 'name' => 'Gửi tin nhắn'],
            ['id' => 160, 'name' => 'Gửi PDF cho quản lý'],
            ['id' => 161, 'name' => 'Xem hợp đồng PDF'],
            ['id' => 162, 'name' => 'Thay đổi quyền cho nhân viên'],
            ['id' => 163, 'name' => 'Xóa quyền'],
            ['id' => 164, 'name' => 'Gửi bản PDF cho giám đốc'],
            ['id' => 165, 'name' => 'Xem chi tiết hợp đồng (PDF)'],
            ['id' => 166, 'name' => 'Xác nhận hợp đồng'],
            ['id' => 167, 'name' => 'Từ chối hợp đồng'],
            ['id' => 170, 'name' => 'Lịch sử bán hàng'],
            ["id" => 171, "name" => "Danh sách đơn hợp đồng"],
            ["id" => 172, "name" => "Thêm biến thể cho nhà cung cấp"],
            ["id" => 173, "name" => "Xóa biến thể của nhà cung cấp"],
            ["id" => 174, "name" => "Lấy danh sách biến thể theo nhà cung cấp"],
            ["id" => 175, "name" => "Thống kê doanh thu"],
            ["id" => 176, "name" => "Thống kê doanh thu theo khoảng thời gian"],
            ["id" => 177, "name" => "Thống kê đơn hàng"],
            ["id" => 178, "name" => "Thống kê doanh thu chi tiết"],
            ["id" => 179, "name" => "API thống kê đơn hàng"],
            ["id" => 180, "name" => "Thống kê sản phẩm"],
            ["id" => 181, "name" => "Thống kê đối tác"],
            ["id" => 182, "name" => "Lọc thống kê đối tác"],
            ["id" => 183, "name" => "Xuất hóa đơn đơn hàng"],
            ["id" => 184, "name" => "Thêm đơn hàng mới"],
            ["id" => 185, "name" => "Yêu cầu hoàn tiền đơn hàng"],
            ["id" => 186, "name" => "Cập nhật phân công"],
        ]);
    }
}
