<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class PermissionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table(table: 'permissions')->insert([
                ['id' => 1, 'name' => 'Xem trang dashboard'],
                ['id' => 2, 'name' => 'Thêm chức vụ'],
                ['id' => 3, 'name' => 'Phân quyền'],
                ['id' => 4, 'name' => 'Xem danh sách quyền truy cập'],
                ['id' => 5, 'name' => 'Xem danh sách nhân viên'],
                ['id' => 6, 'name' => 'Thêm mới nhân viên'],
                ['id' => 7, 'name' => 'Lưu nhân viên mới'],
                ['id' => 8, 'name' => 'Sửa thông tin nhân viên'],
                ['id' => 9, 'name' => 'Cập nhật thông tin nhân viên'],
                ['id' => 10, 'name' => 'Xem danh sách nhà phân phối'],
                ['id' => 11, 'name' => 'Xem danh sách nhà phân phối đã ẩn'],
                ['id' => 12, 'name' => 'Khôi phục nhà phân phối'],
                ['id' => 13, 'name' => 'Thêm mới nhà phân phối'],
                ['id' => 14, 'name' => 'Lưu nhà phân phối mới'],
                ['id' => 15, 'name' => 'Sửa nhà phân phối'],
                ['id' => 16, 'name' => 'Cập nhật nhà phân phối'],
                ['id' => 17, 'name' => 'Xóa nhà phân phối'],
                ['id' => 18, 'name' => 'Xem danh sách nhà cung cấp'],
                ['id' => 19, 'name' => 'Thêm mới nhà cung cấp'],
                ['id' => 20, 'name' => 'Lưu nhà cung cấp mới'],
                ['id' => 21, 'name' => 'Sửa nhà cung cấp'],
                ['id' => 22, 'name' => 'Cập nhật nhà cung cấp'],
                ['id' => 23, 'name' => 'Lấy địa chỉ theo ID khách hàng'],
                ['id' => 24, 'name' => 'Đặt địa chỉ mặc định'],
                ['id' => 25, 'name' => 'Lấy địa chỉ khách hàng'],
                ['id' => 26, 'name' => 'Xóa địa chỉ'],
                ['id' => 27, 'name' => 'Lấy thông tin địa chỉ'],
                ['id' => 28, 'name' => 'Xem danh sách nhân viên'],
                ['id' => 29, 'name' => 'Thêm mới nhân viên'],
                ['id' => 30, 'name' => 'Lưu nhân viên mới'],
                ['id' => 31, 'name' => 'Sửa thông tin nhân viên'],
                ['id' => 32, 'name' => 'Cập nhật thông tin nhân viên'],
                ['id' => 33, 'name' => 'Xem danh sách thanh trượt'],
                ['id' => 34, 'name' => 'Thêm mới thanh trượt'],
                ['id' => 35, 'name' => 'Lưu thanh trượt mới'],
                ['id' => 36, 'name' => 'Xem chi tiết thanh trượt'],
                ['id' => 37, 'name' => 'Sửa thanh trượt'],
                ['id' => 38, 'name' => 'Cập nhật thanh trượt'],
                ['id' => 39, 'name' => 'Xóa thanh trượt'],
                ['id' => 40, 'name' => 'Xem danh sách thương hiệu'],
                ['id' => 41, 'name' => 'Thêm mới thương hiệu'],
                ['id' => 42, 'name' => 'Lưu thương hiệu mới'],
                ['id' => 43, 'name' => 'Sửa thương hiệu'],
                ['id' => 44, 'name' => 'Cập nhật thương hiệu'],
                ['id' => 45, 'name' => 'Xem danh sách hợp đồng'],
                ['id' => 46, 'name' => 'Thêm mới hợp đồng'],
                ['id' => 47, 'name' => 'Lưu hợp đồng mới'],
                ['id' => 48, 'name' => 'Sửa hợp đồng'],
                ['id' => 49, 'name' => 'Cập nhật hợp đồng'],
                ['id' => 50, 'name' => 'Gửi xác nhận cho quản lý'],
                ['id' => 51, 'name' => 'Gửi xác nhận cho khách hàng'],
                ['id' => 52, 'name' => 'Xác nhận hợp đồng'],
                ['id' => 53, 'name' => 'Từ chối hợp đồng'],
                ['id' => 54, 'name' => 'Khách hàng phê duyệt hợp đồng'],
                ['id' => 55, 'name' => 'Khách hàng từ chối hợp đồng'],
                ['id' => 56, 'name' => 'Khách hàng phê duyệt hợp đồng với token'],
                ['id' => 57, 'name' => 'Khách hàng từ chối hợp đồng với token'],
                ['id' => 58, 'name' => 'Sửa hợp đồng theo số hợp đồng'],
                ['id' => 59, 'name' => 'Cập nhật hợp đồng theo số hợp đồng'],
                ['id' => 60, 'name' => 'Xem danh sách bán hàng'],
                ['id' => 61, 'name' => 'Thêm đơn hàng'],
                ['id' => 62, 'name' => 'Lưu đơn hàng mới'],
                ['id' => 63, 'name' => 'Sửa đơn hàng'],
                ['id' => 64, 'name' => 'Cập nhật đơn hàng'],
                ['id' => 65, 'name' => 'Cập nhật trạng thái đơn hàng'],
                ['id' => 66, 'name' => 'Xem chi tiết đơn hàng'],
                ['id' => 67, 'name' => 'Yêu cầu hủy đơn hàng'],
                ['id' => 68, 'name' => 'Xem danh sách xe'],
                ['id' => 69, 'name' => 'Thêm mới xe'],
                ['id' => 70, 'name' => 'Lưu xe mới'],
                ['id' => 71, 'name' => 'Sửa xe'],
                ['id' => 72, 'name' => 'Cập nhật xe'],
                ['id' => 73, 'name' => 'Xem danh sách loại hợp đồng'],
                ['id' => 74, 'name' => 'Thêm loại hợp đồng'],
                ['id' => 75, 'name' => 'Lưu loại hợp đồng mới'],
                ['id' => 76, 'name' => 'Sửa loại hợp đồng'],
                ['id' => 77, 'name' => 'Cập nhật loại hợp đồng'],
                ['id' => 78, 'name' => 'Xem danh sách khách hàng'],
                ['id' => 79, 'name' => 'Xem danh sách sản phẩm'],
                ['id' => 80, 'name' => 'Thêm mới sản phẩm'],
                ['id' => 81, 'name' => 'Lưu sản phẩm mới'],
                ['id' => 82, 'name' => 'Sửa sản phẩm'],
                ['id' => 83, 'name' => 'Cập nhật sản phẩm'],
                ['id' => 84, 'name' => 'Xem danh sách đơn hàng nhập'],
                ['id' => 85, 'name' => 'Thêm đơn hàng nhập'],
                ['id' => 86, 'name' => 'Lưu đơn hàng nhập mới'],
                ['id' => 87, 'name' => 'Sửa đơn hàng nhập'],
                ['id' => 88, 'name' => 'Cập nhật đơn hàng nhập'],
                ['id' => 89, 'name' => 'Xem chi tiết đơn hàng nhập'],
                ['id' => 90, 'name' => 'Yêu cầu hủy đơn hàng nhập'],
                ['id' => 91, 'name' => 'Lấy danh sách yêu cầu hủy đang chờ'],
                ['id' => 92, 'name' => 'Hủy đơn hàng nhập'],
                ['id' => 93, 'name' => 'Xác nhận đơn hàng nhập'],
                ['id' => 94, 'name' => 'Cập nhật trạng thái tự động'],
                ['id' => 95, 'name' => 'Lấy danh sách yêu cầu mới đang chờ'],
                ['id' => 96, 'name' => 'Kiểm tra trạng thái đơn hàng nhập'],
                ['id' => 97, 'name' => 'Cập nhật trạng thái đơn hàng nhập'],
                ['id' => 98, 'name' => 'Từ chối đơn hàng nhập'],
                ['id' => 99, 'name' => 'Xem danh sách đơn vị'],
                ['id' => 100, 'name' => 'Thêm mới đơn vị'],
                ['id' => 101, 'name' => 'Lưu đơn vị mới'],
                ['id' => 102, 'name' => 'Sửa đơn vị'],
                ['id' => 103, 'name' => 'Cập nhật đơn vị'],
                ['id' => 104, 'name' => 'Xóa đơn vị'],
                ['id' => 105, 'name' => 'Xem danh sách loại xe'],
                ['id' => 106, 'name' => 'Thêm mới loại xe'],
                ['id' => 107, 'name' => 'Lưu loại xe mới'],
                ['id' => 108, 'name' => 'Sửa loại xe'],
                ['id' => 109, 'name' => 'Cập nhật loại xe'],
                ['id' => 110, 'name' => 'Xóa loại xe'],
                ['id' => 111, 'name' => 'Xem danh sách danh mục'],
                ['id' => 112, 'name' => 'Thêm mới danh mục'],
                ['id' => 113, 'name' => 'Lưu danh mục mới'],
                ['id' => 114, 'name' => 'Sửa danh mục'],
                ['id' => 115, 'name' => 'Cập nhật danh mục'],
                ['id' => 116, 'name' => 'Xóa danh mục'],
                ['id' => 117, 'name' => 'Xem danh sách xếp hạng khách hàng'],
                ['id' => 118, 'name' => 'Thêm mới xếp hạng khách hàng'],
                ['id' => 119, 'name' => 'Lưu xếp hạng khách hàng mới'],
                ['id' => 120, 'name' => 'Sửa xếp hạng khách hàng'],
                ['id' => 121, 'name' => 'Cập nhật xếp hạng khách hàng'],
                ['id' => 122, 'name' => 'Xóa xếp hạng khách hàng'],
                ['id' => 123, 'name' => 'Xem danh sách chuyến xe'],
                ['id' => 124, 'name' => 'Thêm mới chuyến xe'],
                ['id' => 125, 'name' => 'Lưu chuyến xe mới'],
                ['id' => 126, 'name' => 'Sửa chuyến xe'],
                ['id' => 127, 'name' => 'Cập nhật chuyến xe'],
                ['id' => 128, 'name' => 'Xóa chuyến xe'],
                ['id' => 129, 'name' => 'Xem chi tiết chuyến xe'],
                ['id' => 130, 'name' => 'Xem logs'],
                ['id' => 131, 'name' => 'Xem danh sách tồn kho'],
                ['id' => 132, 'name' => 'Xuất variations'],
                ['id' => 133, 'name' => 'Nhập variations'],
                ['id' => 134, 'name' => 'Lưu tồn kho'],
                ['id' => 135, 'name' => 'Lấy chi tiết tồn kho'],
                ['id' => 136, 'name' => 'Lịch sử nhập hàng'],
                ['id' => 137, 'name' => 'Xem danh sách loại biến thể'],
                ['id' => 138, 'name' => 'Thêm mới loại biến thể'],
                ['id' => 139, 'name' => 'Lưu loại biến thể mới'],
                ['id' => 140, 'name' => 'Thêm giá trị loại biến thể'],
                ['id' => 141, 'name' => 'Sửa loại biến thể'],
                ['id' => 142, 'name' => 'Cập nhật loại biến thể'],
                ['id' => 143, 'name' => 'Khách hàng xác nhận hợp đồng'],
                ['id' => 144, 'name' => 'Khách hàng từ chối hợp đồng']
        ]);
    }
}
